services:
  fastapi-service-miako:
    build: .
    image: mirai-aiko-reborn
    container_name: backend-fastapi
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - secrets/.env
    networks:
      - miako-network

networks:
  full-network-miako:
    driver: bridge
